version: '3.8'

services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -port 8000 -dbPath ./data"
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    volumes:
      - "./dynamodb-volume:/home/dynamodblocal/data"
    ports:
      - "8042:8000"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb